"""Render a GeneratedContract to a correctly-formatted PDF.

WeasyPrint (HTML/CSS -> PDF, backed by Pango/HarfBuzz) does the hard part: it shapes
Arabic and reorders RTL runs correctly when the element is `dir="rtl"` with an Arabic
font (Amiri). We build semantic HTML and let it typeset.

Layouts:
  - Arabic-only / English-only  -> one single-column PDF.
  - Bilingual, "side_by_side"    -> one PDF, each clause EN (left) | AR (right).
  - Bilingual, "sequential"      -> one PDF, full EN section then full AR section.
  - Bilingual, "separate"        -> two PDFs (one EN, one AR).
"""
from __future__ import annotations

import html as _html
from typing import Any

from app.generation.schema import GeneratedContract

# --------------------------------------------------------------------------- #
# Localised labels / boilerplate
# --------------------------------------------------------------------------- #
_L = {
    "en": {
        "dir": "ltr",
        "cls": "en",
        "clause": "Article",
        "parties": "The Parties",
        "between": "This contract is made and entered into between:",
        "preamble": "Preamble",
        "gov": "Governing Law",
        "sign": "Signatures",
        "basis": "Legal basis",
        "place": "Place",
        "date": "Date",
        "signature": "Signature",
        "col": "English",
    },
    "ar": {
        "dir": "rtl",
        "cls": "ar",
        "clause": "المادة",
        "parties": "أطراف العقد",
        "between": "حُرِّر هذا العقد وأُبرم بين:",
        "preamble": "تمهيد",
        "gov": "القانون الواجب التطبيق",
        "sign": "التوقيعات",
        "basis": "الأساس القانوني",
        "place": "المكان",
        "date": "التاريخ",
        "signature": "التوقيع",
        "col": "العربية",
    },
}

_DISCLAIMER = {
    "en": (
        "DRAFT generated by Agent El-Dostor — general legal information, not a substitute "
        "for a licensed Egyptian lawyer. Review every bracketed blank before use."
    ),
    "ar": (
        "مسودة أنشأها «وكيل الدستور» — معلومات قانونية عامة وليست بديلاً عن محامٍ مصري "
        "مرخّص. راجِع كل فراغ بين قوسين قبل الاستخدام."
    ),
}


def _esc(s: Any) -> str:
    return _html.escape("" if s is None else str(s)).replace("\n", "<br>")


# --------------------------------------------------------------------------- #
# CSS
# --------------------------------------------------------------------------- #
def _css() -> str:
    return """
    @page {
        size: A4;
        margin: 2.2cm 2cm 2.4cm 2cm;
        @bottom-center { content: counter(page) " / " counter(pages); font-size: 9pt; color: #666; }
    }
    body { font-family: 'DejaVu Serif', serif; font-size: 11pt; color: #111; line-height: 1.5; }
    .ar { font-family: 'Amiri', serif; direction: rtl; text-align: right; font-size: 12.5pt; }
    .en { font-family: 'DejaVu Serif', serif; direction: ltr; text-align: left; }
    .disclaimer {
        border: 1px solid #c9a227; background: #fdf6e3; color: #6b5900;
        padding: 8px 12px; font-size: 8.5pt; margin-bottom: 16px; line-height: 1.35;
    }
    .disclaimer div + div { margin-top: 3px; }
    h1.title { text-align: center; font-size: 17pt; margin: 4px 0; }
    h1.title.ar { font-size: 18pt; }
    .meta { text-align: center; color: #444; font-size: 10pt; margin-bottom: 14px; }
    h2.section { font-size: 12.5pt; border-bottom: 1px solid #999; padding-bottom: 2px; margin: 18px 0 8px; }
    .party { margin: 4px 0; }
    .party .role { font-weight: bold; }
    .clause { margin: 10px 0; }
    .clause .head { font-weight: bold; margin-bottom: 2px; }
    .basis { font-size: 8.5pt; color: #555; margin-top: 3px; font-style: italic; }
    .lawtext { white-space: normal; }
    /* Side-by-side bilingual */
    table.bi { width: 100%; border-collapse: collapse; table-layout: fixed; }
    table.bi td { width: 50%; vertical-align: top; padding: 8px 10px; border-bottom: 1px solid #e0e0e0; }
    table.bi th { padding: 6px 10px; border-bottom: 2px solid #999; font-size: 10pt; }
    .sign-table { width: 100%; margin-top: 28px; }
    .sign-table td { width: 50%; vertical-align: top; padding: 8px 12px; }
    .sign-line { margin-top: 34px; border-top: 1px solid #333; padding-top: 3px; font-size: 10pt; }
    .pagebreak { break-before: page; }
    """


# --------------------------------------------------------------------------- #
# Fragments
# --------------------------------------------------------------------------- #
def _disclaimer_box(langs: list[str]) -> str:
    rows = "".join(f"<div>{_esc(_DISCLAIMER[l])}</div>" for l in langs)
    return f'<div class="disclaimer">{rows}</div>'


def _party_block(party, lang: str) -> str:
    lab = _L[lang]
    role = _esc(getattr(party, f"role_{lang}"))
    name = _esc(getattr(party, f"name_{lang}"))
    details = _esc(getattr(party, f"details_{lang}"))
    parts = []
    if role or name:
        parts.append(f'<span class="role">{role}</span>{": " if role and name else ""}{name}')
    if details:
        parts.append(f"<br><span>{details}</span>")
    return f'<div class="party {lab["cls"]}">{"".join(parts)}</div>'


def _clause_head(clause, lang: str) -> str:
    lab = _L[lang]
    heading = _esc(getattr(clause, f"heading_{lang}"))
    label = f'{lab["clause"]} ({clause.number})'
    return f'{label}. {heading}' if heading else label


def _basis_line(clause, lang: str) -> str:
    if not clause.legal_basis:
        return ""
    lab = _L[lang]
    refs = "؛ ".join(
        f"{_esc(b.ref)}{(' — ' + _esc(b.law)) if b.law else ''}" for b in clause.legal_basis
    )
    return f'<div class="basis {lab["cls"]}">{lab["basis"]}: {refs}</div>'


def _clause_single(clause, lang: str) -> str:
    lab = _L[lang]
    body = _esc(getattr(clause, f"body_{lang}"))
    return (
        f'<div class="clause {lab["cls"]}">'
        f'<div class="head">{_clause_head(clause, lang)}</div>'
        f'<div class="lawtext">{body}</div>'
        f"{_basis_line(clause, lang)}"
        f"</div>"
    )


def _sign_block(p, lang: str) -> str:
    """A single party's signature block (role, name, signature line)."""
    lab = _L[lang]
    role = _esc(getattr(p, f"role_{lang}")) if p else ""
    name = _esc(getattr(p, f"name_{lang}")) if p else ""
    return (
        f'<div class="{lab["cls"]}"><div>{role}</div><div>{name}</div>'
        f'<div class="sign-line">{lab["signature"]}: ____________________</div></div>'
    )


def _signatures(contract: GeneratedContract, lang: str) -> str:
    """Signatures section for a single-column document: two blocks per row."""
    lab = _L[lang]
    parties = contract.parties[:4] or [None, None]
    cells = [f'<td>{_sign_block(p, lang)}</td>' for p in parties]
    rows = "".join(
        f"<tr>{cells[i]}{cells[i + 1] if i + 1 < len(cells) else '<td></td>'}</tr>"
        for i in range(0, len(cells), 2)
    )
    return f'<h2 class="section {lab["cls"]}">{lab["sign"]}</h2><table class="sign-table">{rows}</table>'


def _signatures_stacked(contract: GeneratedContract, lang: str) -> str:
    """Signatures stacked vertically — for a narrow (bilingual side-by-side) column."""
    lab = _L[lang]
    parties = contract.parties[:4] or [None, None]
    blocks = "".join(f'<div style="margin-top:18px">{_sign_block(p, lang)}</div>' for p in parties)
    return f'<h2 class="section {lab["cls"]}">{lab["sign"]}</h2>{blocks}'


def _section(contract: GeneratedContract, lang: str) -> str:
    """Full single-column contract body in one language."""
    lab = _L[lang]
    title = _esc(getattr(contract, f"title_{lang}")) or (_L[lang]["clause"] + " —")
    meta_bits = []
    if contract.place:
        meta_bits.append(f'{lab["place"]}: {_esc(contract.place)}')
    if contract.date:
        meta_bits.append(f'{lab["date"]}: {_esc(contract.date)}')
    meta = f'<div class="meta {lab["cls"]}">{"  ·  ".join(meta_bits)}</div>' if meta_bits else ""

    parts = [f'<h1 class="title {lab["cls"]}">{title}</h1>', meta]

    if contract.parties:
        parts.append(f'<h2 class="section {lab["cls"]}">{lab["parties"]}</h2>')
        parts.append(f'<div class="{lab["cls"]}">{_esc(lab["between"])}</div>')
        parts += [_party_block(p, lang) for p in contract.parties]

    preamble = _esc(getattr(contract, f"preamble_{lang}"))
    if preamble:
        parts.append(f'<h2 class="section {lab["cls"]}">{lab["preamble"]}</h2>')
        parts.append(f'<div class="{lab["cls"]}">{preamble}</div>')

    parts += [_clause_single(c, lang) for c in contract.clauses]

    gov = _esc(getattr(contract, f"governing_law_{lang}"))
    if gov:
        parts.append(f'<h2 class="section {lab["cls"]}">{lab["gov"]}</h2>')
        parts.append(f'<div class="clause {lab["cls"]}"><div class="lawtext">{gov}</div></div>')

    parts.append(_signatures(contract, lang))
    return "\n".join(parts)


def _side_by_side(contract: GeneratedContract) -> str:
    """Bilingual: each clause EN (left) | AR (right) in a two-column table."""
    en, ar = _L["en"], _L["ar"]
    head = (
        f'<h1 class="title en">{_esc(contract.title_en)}</h1>'
        f'<h1 class="title ar">{_esc(contract.title_ar)}</h1>'
    )
    meta_bits = []
    if contract.place:
        meta_bits.append(f'{en["place"]}: {_esc(contract.place)}')
    if contract.date:
        meta_bits.append(f'{en["date"]}: {_esc(contract.date)}')
    meta = f'<div class="meta">{"  ·  ".join(meta_bits)}</div>' if meta_bits else ""

    rows = [f'<tr><th class="en">{en["col"]}</th><th class="ar">{ar["col"]}</th></tr>']

    # Parties row
    if contract.parties:
        p_en = f'<div class="head en">{en["parties"]}</div>' + "".join(_party_block(p, "en") for p in contract.parties)
        p_ar = f'<div class="head ar">{ar["parties"]}</div>' + "".join(_party_block(p, "ar") for p in contract.parties)
        rows.append(f'<tr><td class="en">{p_en}</td><td class="ar">{p_ar}</td></tr>')

    # Preamble row
    if contract.preamble_en or contract.preamble_ar:
        rows.append(
            f'<tr><td class="en"><div class="head en">{en["preamble"]}</div>{_esc(contract.preamble_en)}</td>'
            f'<td class="ar"><div class="head ar">{ar["preamble"]}</div>{_esc(contract.preamble_ar)}</td></tr>'
        )

    # Clause rows
    for c in contract.clauses:
        left = (
            f'<div class="head en">{_clause_head(c, "en")}</div>'
            f'<div class="lawtext">{_esc(c.body_en)}</div>{_basis_line(c, "en")}'
        )
        right = (
            f'<div class="head ar">{_clause_head(c, "ar")}</div>'
            f'<div class="lawtext">{_esc(c.body_ar)}</div>{_basis_line(c, "ar")}'
        )
        rows.append(f'<tr><td class="en">{left}</td><td class="ar">{right}</td></tr>')

    # Governing-law row
    if contract.governing_law_en or contract.governing_law_ar:
        rows.append(
            f'<tr><td class="en"><div class="head en">{en["gov"]}</div>{_esc(contract.governing_law_en)}</td>'
            f'<td class="ar"><div class="head ar">{ar["gov"]}</div>{_esc(contract.governing_law_ar)}</td></tr>'
        )

    table = f'<table class="bi"><tbody>{"".join(rows)}</tbody></table>'
    # Signatures side by side (EN | AR), stacked within each narrow column.
    sign = (
        f'<table class="sign-table"><tr>'
        f'<td class="en">{_signatures_stacked(contract, "en")}</td>'
        f'<td class="ar">{_signatures_stacked(contract, "ar")}</td></tr></table>'
    )
    return head + meta + table + sign


def _document(body: str, langs: list[str]) -> str:
    root_dir = "rtl" if langs == ["ar"] else "ltr"
    return (
        f'<!DOCTYPE html><html dir="{root_dir}"><head><meta charset="utf-8">'
        f"<style>{_css()}</style></head><body>"
        f"{_disclaimer_box(langs)}{body}</body></html>"
    )


# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #
def _write_pdf(html_str: str) -> bytes:
    from weasyprint import HTML  # imported lazily so the rest of the app runs without it

    return HTML(string=html_str).write_pdf()


def render_contract_pdfs(
    contract: GeneratedContract | dict,
    language: str | None = None,
    layout: str = "side_by_side",
) -> list[tuple[str, bytes]]:
    """Render to PDF(s). Returns [(filename, pdf_bytes), ...] — two items for 'separate'."""
    if isinstance(contract, dict):
        contract = GeneratedContract.model_validate(contract)
    language = language or contract.language or "bilingual"
    ctype = (contract.contract_type or "contract").replace(" ", "_")

    if language == "ar":
        return [(f"{ctype}_contract_ar.pdf", _write_pdf(_document(_section(contract, "ar"), ["ar"])))]
    if language == "en":
        return [(f"{ctype}_contract_en.pdf", _write_pdf(_document(_section(contract, "en"), ["en"])))]

    # bilingual
    if layout == "separate":
        return [
            (f"{ctype}_contract_en.pdf", _write_pdf(_document(_section(contract, "en"), ["en"]))),
            (f"{ctype}_contract_ar.pdf", _write_pdf(_document(_section(contract, "ar"), ["ar"]))),
        ]
    if layout == "sequential":
        body = _section(contract, "en") + '<div class="pagebreak"></div>' + _section(contract, "ar")
        return [(f"{ctype}_contract_bilingual.pdf", _write_pdf(_document(body, ["en", "ar"])))]
    # default: side_by_side
    body = _side_by_side(contract)
    return [(f"{ctype}_contract_bilingual.pdf", _write_pdf(_document(body, ["en", "ar"])))]
